// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClWIl1ylumC7CuqTFXXj0Xhw9E5At7utA',
    appId: '1:463291852736:web:b90cade366221b356b4a25',
    messagingSenderId: '463291852736',
    projectId: 'todo-application-8940d',
    authDomain: 'todo-application-8940d.firebaseapp.com',
    storageBucket: 'todo-application-8940d.appspot.com',
    measurementId: 'G-FSBZV74VWM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGsKWp4bL3OUlBI4TCumAiJYQZzBQjrZg',
    appId: '1:463291852736:android:204b076c7010720f6b4a25',
    messagingSenderId: '463291852736',
    projectId: 'todo-application-8940d',
    storageBucket: 'todo-application-8940d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrKvqQK52Fyj_8Jekpz62eLDKUtCVWpVg',
    appId: '1:463291852736:ios:145c4cfb9561bec96b4a25',
    messagingSenderId: '463291852736',
    projectId: 'todo-application-8940d',
    storageBucket: 'todo-application-8940d.appspot.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrKvqQK52Fyj_8Jekpz62eLDKUtCVWpVg',
    appId: '1:463291852736:ios:6425a84a6f5604696b4a25',
    messagingSenderId: '463291852736',
    projectId: 'todo-application-8940d',
    storageBucket: 'todo-application-8940d.appspot.com',
    iosBundleId: 'com.example.todo.RunnerTests',
  );
}
